/** 화면에 보이는 고정 문구. 결과 문장은 result.ts, 질문은 steps.ts에 있다. */
export const ui = {
  title: '돌아보는 길',
  subtitle: '지나온 커리어를 되짚는 일곱 가지 질문',
  intro: '다음 목적지를 찾기 전에, 지금까지 걸어온 길을 먼저 돌아보세요.',
  duration: '약 7분',
  analyticsNote: '방문 수와 단계 이동 횟수만 익명으로 집계해요. 고른 답과 적은 글은 포함되지 않아요.',
  privacy: '답은 이 기기에만 남아요. 결과 링크를 직접 공유할 때만 링크에 담겨요.',
  scriptureToggle: '성경 구절과 함께 보기',
  scriptureToggleHint: '각 질문의 바탕이 된 성경 구절을 쉬운 말로 풀어 질문 위에 함께 보여 줘요.',
  start: '시작하기',
  startOver: '처음부터 하기',
  resume: '이어서 하기',
  restart: '처음부터 다시 하기',
  next: '다음',
  back: '이전',
  writeOwn: '직접 적기',
  writeOwnPlaceholder: '한 줄로 적어 주세요',
  multiHint: '여러 개 골라도 괜찮아요.',
  needChoice: "하나 이상 골라 주세요. 맞는 답이 없으면 '직접 적기'에 적어도 돼요.",
  needOwnText: "'직접 적기' 칸이 비어 있어요. 내용을 적거나 체크를 해제해 주세요.",
  needStation: '거쳐 온 곳을 한 곳 이상 적어 주세요.',
  addStation: '한 곳 더 추가',
  stationsFull: '일곱 곳을 모두 적었어요.',
  stationFirstPlaceholder: '예: 첫 회사, 전공, 프로젝트',
  stationNextPlaceholder: '그다음 거쳐 온 곳',
  stationLabel: (n: number) => `${n}번째로 거쳐 온 곳`,
  stationsRecap: '거쳐 온 곳',
  stepLabel: (n: number, part?: string) => `7단계 중 ${n}단계${part ? `, ${part}` : ''}.`,
  moveUp: '위로',
  moveDown: '아래로',
  remove: '삭제',
  pathLabel: (done: number, total: number) => `진행 상황: ${total}단계 중 ${done}단계 완료`,
}
